version: '3.8'
services:
  mysql:
    image: mysql:5.7.30
    restart: always
    ports:
      - 3310:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: leboncode
    volumes:
      - admin-leboncode:/var/lib/mysql

###< doctrine/doctrine-bundle ###
volumes:
  admin-leboncode:

###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
